### ISSUE TITLE
As a user, I can click on a marker to see details about a parking location

### ISSUE THREAD

**Issue by abuuzayr** [abuuzayr/motoparker#4]
Acceptance criteria
---------

- [x] Upon clicking a marker, a drawer on the right slides in
- [x] On desktop, the drawer takes up a portion of the page
- [x] On mobile, the drawer takes up the entire screen
- [x] I can close the drawer by clicking on a close button

**Comment by abuuzayr** [comment]
Closed with #55
