### ISSUE TITLE
As a user, I can view details about a parking location

### ISSUE THREAD

**Issue by abuuzayr** [abuuzayr/motoparker#8]
Acceptance criteria
-------------------

These are the details that I can see:

- [x] Name
- [x] Instructions/directions on how to get there
- [x] Parking charges
- [x] Photos of the location
- [x] Last updated timestamp

**Comment by abuuzayr** [comment]
Closed with #51
